# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: https://cran.rstudio.com
cache: packages

before_install:
  - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
  