# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: https://cran.rstudio.com
cache: packages

apt_packages:
  - libudunits2-dev
  - gdal-bin
  - libgdal1-dev
  - libproj-dev

r_binary_packages:
  - rgdal
  
  