# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cran: https://cran.rstudio.com
sudo: false

branches:
  only:
    - master
    
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'


apt_packages:
  - libudunits2-dev
  - gdal-bin
  - libgdal1-dev
  - libproj-dev


r_binary_packages:
  - rgdal
  
  